export const projects = [
  {
    slug: "nordheim-residence",
    title: "Nordheim Residence",
    category: "Residential",
    year: "2024",
    location: "Oslo, Norway",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
    description: "A contemporary family home that harmoniously blends with its natural surroundings. The design emphasizes open spaces and natural light, creating a seamless connection between indoor and outdoor living.",
    materials: "Concrete, Oak Wood, Glass, Steel",
    measurement: "450 sqm / 4,844 sq ft",
    costing: "$2.4M USD",
    challenges: "Integrating the structure into a steep hillside while maintaining panoramic fjord views and ensuring thermal efficiency in harsh Nordic winters.",
    liveLink: "https://example.com/nordheim",
  },
  {
    slug: "the-lund-pavilion",
    title: "The Lund Pavilion",
    category: "Cultural",
    year: "2023",
    location: "Lund, Sweden",
    image: "https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=1200&q=80",
    description: "A cultural pavilion designed to host temporary exhibitions and community events. The structure features a modular design that allows for flexible configurations.",
    materials: "Cross-Laminated Timber, Polycarbonate, Recycled Steel",
    measurement: "320 sqm / 3,444 sq ft",
    costing: "$890K USD",
    challenges: "Creating a sustainable, demountable structure that could be relocated while meeting strict acoustic requirements for musical performances.",
    liveLink: "https://example.com/lund-pavilion",
  },
  {
    slug: "aalto-commercial-tower",
    title: "Aalto Commercial Tower",
    category: "Commercial",
    year: "2023",
    location: "Helsinki, Finland",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80",
    description: "A 24-story commercial tower featuring flexible office spaces with floor-to-ceiling windows. The building incorporates advanced sustainability features including rainwater harvesting and solar panels.",
    materials: "Reinforced Concrete, Aluminum Cladding, Low-E Glass",
    measurement: "18,500 sqm / 199,132 sq ft",
    costing: "$45M USD",
    challenges: "Achieving LEED Platinum certification while maximizing rentable floor area and navigating complex urban planning regulations in a historic district.",
    liveLink: "https://example.com/aalto-tower",
  },
  {
    slug: "bergman-cultural-centre",
    title: "Bergman Cultural Centre",
    category: "Cultural",
    year: "2022",
    location: "Copenhagen, Denmark",
    image: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?w=1200&q=80",
    description: "A multi-purpose cultural center housing a 500-seat theater, gallery spaces, and artist studios. The design pays homage to Danish modernism while incorporating contemporary sustainable practices.",
    materials: "Brick, Blackened Steel, Terrazzo, White Oak",
    measurement: "8,200 sqm / 88,264 sq ft",
    costing: "$28M USD",
    challenges: "Acoustically isolating the theater from the busy urban environment while creating visual connections between interior spaces and the surrounding cityscape.",
    liveLink: "https://example.com/bergman-centre",
  },
]

export type Project = typeof projects[number]
